### ISSUE TITLE
move to fsspec org

### ISSUE THREAD

**Issue by martindurant** [fsspec/sshfs#13]
There was talk of this and other fsspec-compatible implementations being transferred to github.com/fsspec . No rush, merely recording what was previously suggested.

**Comment by efiop** [comment]
@martindurant Done, but I need admin rights to have access to secrets and stuff like that. Could you add me, please?

**Comment by martindurant** [comment]
As a member of the team "maintainers", I think you have everything you need.

**Comment by efiop** [comment]
@martindurant This repo was not automatically added to https://github.com/orgs/fsspec/teams/maintainers/repositories, so I can't do anything here at all until I'm added.

**Comment by martindurant** [comment]
Done! Sorry about that.

**Comment by efiop** [comment]
@martindurant No worries :) Btw, looks like you forgot to select "Maintain" for it it in https://github.com/orgs/fsspec/teams/maintainers/repositories
<img width="951" alt="Screenshot 2021-11-18 at 01 22 03" src="https://user-images.githubusercontent.com/5367102/142298230-0dc8b7c1-8522-4062-ab36-52b8311efc79.png">
 .

**Comment by efiop** [comment]
@martindurant Also, "Maintain" still doesn't have any access to secrets in the repo, which I really do need at least for our repos 🙂 I totally understand and respect that you are trying to keep the org tidy in all senses, but unless you want me to ping you for every occasion (e.g. secrets, new repos like https://github.com/iterative/ossfs being transfered, etc), maybe there is a way to give me a bit more permissions so I could help out 🙂

**Comment by martindurant** [comment]
Makes sense - where do I do that? :)

**Comment by efiop** [comment]
@martindurant I think we need to adjust rights for the whole org for it to be the most hustle-free: https://github.com/orgs/fsspec/people need to adjust role from "Member" to "Owner" (i don't think there are any other options in between 🙁 ).
